language: php

php: 7.3

services: mysql

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-8.3.4.phar
  - composer install --no-interaction --prefer-source
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - vendor/bin/phpunit
