language: php

php: 7.3

services: mysql

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-6.5.14.phar
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
